### ISSUE TITLE
not working :)

### ISSUE THREAD

**Issue by TheRealDeveloper** [KingOfTurkey38/Voting38#11]

**Comment by KingOfTurkey38** [comment]
Explain.

**Comment by TheRealDeveloper** [comment]
Its not Running

**Comment by TheRealDeveloper** [comment]
and Key is APIKEY ?

**Comment by TheRealDeveloper** [comment]
[Server thread/CRITICAL]: Error: "Class "SOFe\AwaitStd\AwaitStd" not found" (EXCEPTION) in "plugins/Voting3/src/kingofturkey38/voting38/Main" at line 57

**Comment by TukangM** [comment]
> and Key is APIKEY ?

api key from this web https://minecraftpocket-servers.com

I'm lazy to teach stupid people

**Comment by KingOfTurkey38** [comment]
> [Server thread/CRITICAL]: Error: "Class "SOFe\AwaitStd\AwaitStd" not found" (EXCEPTION) in "plugins/Voting3/src/kingofturkey38/voting38/Main" at line 57

Use the builds from poggit, do not directly git clone if you don't know what you're doing.

**Comment by SiahRBLX** [comment]
Yeah the issue was when using "git clone" folder etc.. gives that error but using .phar works fine
