### ISSUE TITLE
Error after set key

### ISSUE THREAD

**Issue by HeXeRMC** [KingOfTurkey38/Voting38#3]
"SOFe\AwaitStd\AwaitStd" not found" (EXCEPTION) in "plugins/Voting38[PM4]/src/kingofturkey38/voting38/Main" at line 52
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginBase(137): kingofturkey38\voting38\Main->onEnable()
  #1 pmsrc/src/plugin/PluginManager(438): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #2 pmsrc/src/Server(1383): pocketmine\plugin\PluginManager->enablePlugin(object kingofturkey38\voting38\Main#23971)
  #3 pmsrc/src/Server(1009): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#23437)
  #4 pmsrc/src/PocketMine(303): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[14] /root/newRvmp/, string[22] /root/newRvmp/plugins/)
  #5 pmsrc/src/PocketMine(326): pocketmine\server()
  #6 pmsrc(11): require(string[58] phar:///root/newRvmp/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by KingOfTurkey38** [comment]
Are you using the latest phar from https://poggit.pmmp.io/ci/KingOfTurkey38/Voting38/~ ?

**Comment by HeXeRMC** [comment]
> Are you using the latest phar from https://poggit.pmmp.io/ci/KingOfTurkey38/Voting38/~ ?

No, I was using the main here on github. Thanks
