### ISSUE TITLE
How to change vote reward?

### ISSUE THREAD

**Issue by Pinkglitter2216** [KingOfTurkey38/Voting38#4]
Hello, 
i cant change the vote reward in the config. Players always claim 64 diamonds. Please help me. Thanks!

**Comment by KingOfTurkey38** [comment]
You can configure command rewards https://github.com/KingOfTurkey38/Voting38/blob/9c95c2e46eb561fbad7b4b476c7d09d4106578b2/resources/config.yml#L11

**Comment by Pinkglitter2216** [comment]
Ahhh yes thanks, look like i am blind xD . But can i change the rewards? That players becoms every day another reward? 
Can I set players to always randomly get a different reward?

**Comment by KingOfTurkey38** [comment]
Unfortunately, that feature is not implemented. You can make your own plugin that'll do that

**Comment by Pinkglitter2216** [comment]
Ok thank you!
