### ISSUE TITLE
PLAYER name bug

### ISSUE THREAD

**Issue by ilovepackets** [KingOfTurkey38/Voting38#5]
{username} works but users with a space in ther ign it doesnt work

**Comment by KingOfTurkey38** [comment]
You can fix that issue by wrapping the username with "" for example:
`- give "{username}" diamond`

**Comment by ilovepackets** [comment]
2022-03-09 [10:07:15.942] [Server thread/INFO]: Enabling Voting38 v0.0.1
2022-03-09 [10:07:15.942] [Server thread/CRITICAL]: pocketmine\utils\ConfigLoadException: "Failed to parse config /home/gameserver/servers/serveur3/minecraftbedrock/plugin_data/Voting38/config.yml: yaml_parse(): parsing error encountered during parsing: did not find expected '-' indicator (line 12, column 26), context while parsing a block collection (line 12, column 3)" (EXCEPTION) in "pmsrc/src/utils/ConfigLoadException" at line 29
--- Stack trace ---
#0 pmsrc/src/utils/Config(188): pocketmine\utils\ConfigLoadException::wrap(string[82] /home/gameserver/servers/serveur3/minecraftbedrock/plugin_data/Voting38/config.y, object ErrorException#28493)
#1 pmsrc/src/utils/Config(121): pocketmine\utils\Config->load(string[82] /home/gameserver/servers/serveur3/minecraftbedrock/plugin_data/Voting38/config.y, integer -1, array[0])
#2 pmsrc/src/plugin/PluginBase(300): pocketmine\utils\Config->__construct(string[82] /home/gameserver/servers/serveur3/minecraftbedrock/plugin_data/Voting38/config.y)
#3 pmsrc/src/plugin/PluginBase(281): pocketmine\plugin\PluginBase->reloadConfig()
#4 plugins/Voting38_dev-7.phar/src/kingofturkey38/voting38/Main(48): pocketmine\plugin\PluginBase->getConfig()
#5 pmsrc/src/plugin/PluginBase(137): kingofturkey38\voting38\Main->onEnable()
#6 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#7 pmsrc/src/Server(1385): pocketmine\plugin\PluginManager->enablePlugin(object kingofturkey38\voting38\Main#25260)
#8 pmsrc/src/Server(1011): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24906)
#9 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[51] /home/gameserver/servers/serveur3/minecraftbedrock/, string[59] /home/gameserver/servers/serveur3/minecraftbedrock/plugins/)
#10 pmsrc/src/PocketMine(327): pocketmine\server()
#11 pmsrc(11): require(string[95] phar:///home/gameserver/servers/serveur3/minecraftbedrock/PocketMine-MP.phar/src)
--- Previous ---
ErrorException: "yaml_parse(): parsing error encountered during parsing: did not find expected '-' indicator (line 12, column 26), context while parsing a block collection (line 12, column 3)" (EXCEPTION) in "pmsrc/src/utils/Config" at line 186
#0 (): pocketmine\errorhandler\ErrorToExceptionHandler::pocketmine\errorhandler\{closure}(integer 2, string[174] yaml_parse(): parsing error encountered during parsing: did not find expected '-, string[97] phar:///home/gameserver/servers/serveur3/minecraftbedrock/PocketMine-MP.phar/src, integer 186)
#1 pmsrc/src/utils/Config(186): yaml_parse(string[293] ---.key: "bTPjIrWdd4K6Vh5hB9kZ6VgVbXuBQ4VM2vz".autoclaim: true..vote_announcemen)
#2 pmsrc/vendor/pocketmine/errorhandler/src/ErrorToExceptionHandler(103): pocketmine\utils\Config->pocketmine\utils\{closure}()
#3 pmsrc/src/utils/Config(186): pocketmine\errorhandler\ErrorToExceptionHandler::trap(object Closure#28456)
#4 pmsrc/src/utils/Config(121): pocketmine\utils\Config->load(string[82] /home/gameserver/servers/serveur3/minecraftbedrock/plugin_data/Voting38/config.y, integer -1, array[0])
#5 pmsrc/src/plugin/PluginBase(300): pocketmine\utils\Config->__construct(string[82] /home/gameserver/servers/serveur3/minecraftbedrock/plugin_data/Voting38/config.y)
#6 pmsrc/src/plugin/PluginBase(281): pocketmine\plugin\PluginBase->reloadConfig()
#7 plugins/Voting38_dev-7.phar/src/kingofturkey38/voting38/Main(48): pocketmine\plugin\PluginBase->getConfig()
#8 pmsrc/src/plugin/PluginBase(137): kingofturkey38\voting38\Main->onEnable()
#9 pmsrc/src/plugin/PluginManager(437): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#10 pmsrc/src/Server(1385): pocketmine\plugin\PluginManager->enablePlugin(object kingofturkey38\voting38\Main#25260)
#11 pmsrc/src/Server(1011): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#24906)
#12 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[51] /home/gameserver/servers/serveur3/minecraftbedrock/, string[59] /home/gameserver/servers/serveur3/minecraftbedrock/plugins/)
#13 pmsrc/src/PocketMine(327): pocketmine\server()
#14 pmsrc(11): require(string[95] phar:///home/gameserver/servers/serveur3/minecraftbedrock/PocketMine-MP.phar/src)
--- End of exception information ---

**Comment by ilovepackets** [comment]
this is error i get when i do "{username}"

**Comment by KingOfTurkey38** [comment]
Can you send the config

**Comment by ilovepackets** [comment]
---
key: "bTPjIrWdd4K6Vh5hB9kZ6VgVbXuBQ4VM2vz"
autoclaim: true

vote_announcement: "§c§l{username} has voted and received a Voting Crate"

message_not_voted: "§cYou haven't voted today"
message_voted: "§aYou have already voted today"


commands:
  - "pcrate give Common "{username}" 2"
...

**Comment by KingOfTurkey38** [comment]
replace `"pcrate give Common "{username}" 2"` with `pcrate give Common "{username}" 2`

**Comment by KingOfTurkey38** [comment]
No response in a week so closing this issue.
